### Path: "/"
GET http://localhost:3333/ HTTP/1.1

### Path: "/stats/x"
GET http://localhost:3333/stats HTTP/1.1


### QRCODE - "/qrcode/:hash"
GET http://localhost:3333/api/links/ HTTP/1.1
Accept: application/json



### RESOLVES - "/:hash"
GET http://localhost:3333/K_frzHL HTTP/1.1
Accept: application/json

### QRCODE - "/qrcode/:hash"
GET http://localhost:3333/api/links/qrcode/K_frzHL HTTP/1.1
Accept: application/json

### FORMAT - "/format/:hash"
GET http://localhost:3333/api/links/format/K_frzHL/?type=json HTTP/1.1
Accept: application/json

### CREATE - "/api/links"
POST http://localhost:3333/api/links HTTP/1.1
Content-Type: application/json
Accept: application/json

{
	"href": "https://www.google.com/?q=Node.js"
}
