### Path: "/"
GET http://localhost:3333/ HTTP/1.1
Accept: application/json



### REDIRECTINGS - "/:hash"
GET http://localhost:3333/J-gyaZGb HTTP/1.1
Accept: application/json

### QRCODE - "/qrcode/:hash"
GET http://localhost:3333/api/links/qrcode/J-gyaZGb HTTP/1.1
Accept: application/json

### FORMAT - "/format/:hash"
GET http://localhost:3333/api/links/format/J-gyaZGb/?type=json HTTP/1.1
Accept: application/json



### CREATE - "/api/links"
POST http://localhost:3333/api/links HTTP/1.1
Accept: application/json
Content-Type: application/json

{
	"href": "https://www.google.com/?q=Axios.js"
}



### CSP REPORT VIOLATION (TESTING)
POST http://localhost:3333/report-violation HTTP/1.1
Accept: application/json
Content-Type: application/csp-report

{
	"csp-report": {
		"document-uri": "http://localhost:3333"
	}
}
